# Conda environment for MADE
name: made
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit
  - tensorflow
  - scikit-learn
  - pandas
  - tqdm
  - scipy
  - matplotlib
  - ipykernel
  - seaborn
  - pytorch::pytorch
  - torchvision
  - captum
